5:00:24 PM Monday, February 22, 2021
<Class Name Error
<Messages>
System.IO.IOException: The process cannot access the file 'C:\Users\wdxadmin\source\repos\Remediation\Data\bin\Debug\WrongData.csv' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents)
   at Remediation.GetCSV.ImportBadData(DataTable badData)
   at Remediation.GetCSV.StartUp(IOrganizationService service)
   at Data.Program.Main() in C:\Users\wdxadmin\source\repos\Remediation\Data\Program.cs:line 19
----
